// Code generated by tools. DO NOT EDIT!
package constant
import (
	"bytes"
	"database/sql/driver"
	
	"github.com/shrewx/enum"
)

func (v Job) Int() int {
	return int(v)
}

func (v Job) String() string {
	switch v { 
	case JOB__DOCTOR:
		return "DOCTOR"
	case JOB__TEACHER:
		return "TEACHER"
	case JOB__DRIVER:
		return "DRIVER"
	}
	return ""
}

func (v Job) Label() string {
	switch v { 
	case JOB__DOCTOR:
		return "医生"
	case JOB__TEACHER:
		return "教师"
	case JOB__DRIVER:
		return "司机"
	}
	return ""
}

func (v Job) Values() []enum.Enum {
	return []enum.Enum{ JOB__DOCTOR,JOB__TEACHER,JOB__DRIVER }
}

func (v Job) Type() string {
	return "github.com/shrewx/toolx/__example__/constant.Job"
}

func (v Job) MarshalText() ([]byte, error) {
	switch v {
	case JOB__DOCTOR,JOB__TEACHER,JOB__DRIVER:
		return []byte(v.String()), nil
	default:
		return nil, enum.InvalidTypeError
	}
}

func (v *Job) UnmarshalText(text []byte) error {
	switch string(bytes.ToUpper(text)) { 
	case JOB__DOCTOR.String():
		*v = JOB__DOCTOR
	case JOB__TEACHER.String():
		*v = JOB__TEACHER
	case JOB__DRIVER.String():
		*v = JOB__DRIVER
	default:
		return enum.InvalidTypeError
	}

	return nil
}

func (v *Job) Scan(value interface{}) error {
	*v = Job(value.(int))
	return nil
}

func (v *Job) Value() (driver.Value, error) {
	return int(*v), nil
}
